FROM node:22-alpine3.19

# Install necessary dependencies in a single step
RUN apk update && apk upgrade && apk add --no-cache git libc6-compat

# Create app directory
WORKDIR /app

# Configure npm global cache (before installing dependencies)
RUN mkdir -p ~/.npm-global && npm config set cache ~/.npm-global

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm i

COPY migrations/ /app/migrations
COPY knexfile.js /app/knexfile.js

CMD ["npx", "knex", "migrate:latest"]